stages:
  # - concurrency_check
  - build
  - test
  - destroy

default:
  tags:
    - cypress

# concurrency_check:
#   stage: concurrency_check
#   script:
#     - |
#       echo "Check for other pipelines"
#       RUNNING=$(curl --silent --header "PRIVATE-TOKEN: $API_TOKEN" \
#         "https://git.berg-systems.ch/api/v4/projects/${CI_PROJECT_ID}/pipelines?ref=${CI_COMMIT_REF_NAME}&status=running" \
#         | jq '. | length')
#
#       if [ "${RUNNING}" -gt 1 ]; then
#         echo "There is another pipeline. Cancelling this one"
#         curl --silent --request POST --header "PRIVATE-TOKEN: $API_TOKEN" \
#           "https://git.berg-systems.ch/api/v4/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/cancel"
#       else
#         echo "No other pipelines. Continue.."
#       fi

build:
  stage: build
  # dependencies:
  #   - concurrency_check
  script:
    - curl -L https://github.com/wavelog/wavelog/archive/refs/heads/dev.tar.gz | tar xz --strip-components=1 -C ./wavelog
    - npm install
    - docker compose -f cypress_testserver.yml up -d 

test:
  stage: test
  dependencies:
    - build
  script:
    - npm install
    - export CYPRESS_baseUrl="http://localhost:${CI_PIPELINE_ID}/"
    - npx cypress run
  artifacts:
    when: on_failure
    reports:
      junit: results/junit-*.xml
    paths:
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 1 week

destroy:
  stage: destroy
  script:
    - docker compose -f cypress_testserver.yml down
  when: always
