stages:
  - prepare
  - build
  - test
  - destroy

prepare:
  stage: prepare
  script:
    - git remote add upstream https://github.com/wavelog/wavelog.git
    - git fetch upstream
    - git merge upstream/dev
    - npm install

build:
  stage: build
  script:
    - docker compose -f cypress_testserver.yml up -d 

test:
  stage: test
  script:
    - npx cypress run
  artifacts:
    reports:
      junit: results/junit-*.xml
    paths:
      - results/
    expire_in: 4 week

destroy:
  stage: destroy
  script:
    - docker compose -f cypress_testserver.yml down