networks:
  wavelog_testnet:

services:
  wavelog-web:
    build: .
    ports:
      - "8087:80"
    depends_on:
      - wavelog-db
    networks:
      - mynet

  wavelog-db:
    image: mariadb:latest
    container_name: wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog
    networks:
      - wavelog_testnet