networks:
  wavelog_testnet:
    name: wavelog_testnet_${CI_PIPELINE_ID}

services:
  wavelog-web:
    build: /tmp/wavelog-${CI_PIPELINE_ID}
    image: wavelog-web:${CI_PIPELINE_ID}
    ports:
      - "${CI_PIPELINE_ID}:80"
    container_name: wavelog-web-${CI_PIPELINE_ID}
    depends_on:
      - wavelog-db
    networks:
      - wavelog_testnet

  wavelog-db:
    container_name: wavelog-db-${CI_PIPELINE_ID}
    image: mariadb:11.3
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog
    networks:
      - wavelog_testnet